# Generated by Django 3.2.3 on 2021-09-22 17:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 9, 22, 22, 32, 25, 871346))),
                ('qty', models.IntegerField()),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_project.location')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_project.product')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_project.location')),
            ],
        ),
    ]
