# Generated by Django 3.2.3 on 2021-09-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='location',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductMovement',
        ),
    ]
