# Generated by Django 3.2.3 on 2021-09-23 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0003_location_product_productmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmovement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 7, 55, 17, 466972)),
        ),
    ]
