# Generated by Django 3.2.3 on 2021-09-23 02:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0004_alter_productmovement_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmovement',
            name='from_location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_project.location'),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 7, 55, 29, 734204)),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_project.location'),
        ),
    ]
