# Generated by Django 3.2.3 on 2021-09-23 03:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0006_auto_20210923_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_project.location'),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 9, 13, 44, 233488)),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_project.location'),
        ),
    ]
